//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Biblioteca1Entities : DbContext
    {
        public Biblioteca1Entities()
            : base("name=Biblioteca1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autors { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Editora> Editoras { get; set; }
        public virtual DbSet<EmprestimoLivro> EmprestimoLivroes { get; set; }
        public virtual DbSet<Livro> Livroes { get; set; }
        public virtual DbSet<LivroAutor> LivroAutors { get; set; }
        public virtual DbSet<EmprestimoEstado> EmprestimoEstadoes { get; set; }
        public virtual DbSet<Utilizador> Utilizadors { get; set; }
        public virtual DbSet<Emprestimo> Emprestimoes { get; set; }
    }
}
