//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emprestimo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emprestimo()
        {
            this.EmprestimoLivroes = new HashSet<EmprestimoLivro>();
        }
    
        public int Id { get; set; }
        public int UtilizadorId { get; set; }
        public System.DateTime DataEmprestimo { get; set; }
        public Nullable<System.DateTime> DataDevolucaoPrevista { get; set; }
        public Nullable<System.DateTime> DataDevolucaoReal { get; set; }
        public int EstadoId { get; set; }
    
        public virtual Utilizador Utilizador { get; set; }
        public virtual EmprestimoEstado EmprestimoEstado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmprestimoLivro> EmprestimoLivroes { get; set; }
    }
}
