//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LivroAutor
    {
        public int LivroId { get; set; }
        public int AutorId { get; set; }
        public int OrdemAutoria { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Livro Livro { get; set; }
    }
}
